name = "aide"
version = "0.1.0"

description = "Build Model Context Protocol (MCP) Servers (clients coming soon)."
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "aide" }
links = []

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
oas_generator_utils = ">= 1.0.0 and < 2.0.0"
# oas is used for json_schema
oas = ">= 7.2.0 and < 8.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
oas_generator = ">= 2.1.1 and < 3.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
